= Test Environment

*Blazing fast smart contract testing.* One-line setup for an awesome testing experience.

* Near-instant start up: have your code running in under 2s after typing `npm test`.
* Test runner agnostic – from the familiarity of Mocha, to xref:choosing-a-test-runner.adoc#parallel-tests[_parallel tests_] using Jest or Ava!
* Non-opinionated: use either https://www.npmjs.com/package/@truffle/contract[`@truffle/contract`] or https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html[`web3-eth-contract`] as you see fit.
* First class support for the xref:test-helpers::index.adoc[OpenZeppelin Test Helpers].
* Highly configurable: from gas limit and initial balance, to complex custom web3 providers.
* No global variables, no hacks.

_Test Environment is the result of our learnings while developing the xref:contracts::index.adoc[OpenZeppelin Contracts], combining best practices and the tools we've come to rely on over the years. We think you'll love it!_

== Overview

=== Installation

```bash
$ npm install --save-dev @openzeppelin/test-environment
```

=== Usage

By including `require('@openzeppelin/test-environment')` in your test files, a local https://github.com/trufflesuite/ganache-core[ganache-powered blockchain] with unlocked accounts will be spun up, and all tools configured to work with it.

```javascript
const { accounts, contract } = require('@openzeppelin/test-environment');
const [ owner ] = accounts;

const { expect } = require('chai');

const MyContract = contract.fromArtifact('MyContract'); // Loads a compiled contract

describe('MyContract', function () {
  it('deployer is owner', async function () {
    const myContract = await MyContract.new({ from: owner });
    expect(await myContract.owner()).to.equal(owner);
  });
});
```

If you're used to `truffle test`, this probably looks very familiar. Follow our guide on xref:migrating-from-truffle.adoc[migrating from Truffle] to have your project running with Test Environment in a breeze!

_Note: if you'd rather not rely on truffle contracts and use web3 contract types directly, worry not: you can xref:getting-started.adoc#configuration[configure Test Environment] to use the `web3-eth-contract` abstraction._

== Learn More

* Check out xref:getting-started.adoc[Getting Started] to use Test Environment in a new project.
* If you are currently using `truffle test`, head instead to xref:migrating-from-truffle.adoc[Migrating from Truffle].
* The xref:choosing-a-test-runner.adoc[Choosing a Test Runner] guide will teach you how to use each of the different runners.
* For detailed usage information, take a look at the xref:api.adoc[API Reference].
