= OpenZeppelin Test Environment

*Blazing fast smart contract testing.* One-line setup for an awesome testing experience.

* Near-instant start up: have your code running in under 2s after typing `npm test`.
* Test runner agnostic – from the familiarity of Mocha, to _parallel tests_ using Jest or Ava!
* Non-opinionated: use either https://www.npmjs.com/package/@truffle/contract[`@truffle/contract`] or https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html[`web3-eth-contract`] as you see fit.
* First class support for the https://github.com/OpenZeppelin/openzeppelin-test-helpers[OpenZeppelin Test Helpers].
* Highly configurable: from gas limit and initial balance, to complex custom web3 providers.
* No global variables, no hacks.

_`test-environment` is the result of our learnings while developing the https://github.com/OpenZeppelin/openzeppelin-contracts[OpenZeppelin Contracts], combining best practices and the tools we've come to rely on over the years. We think you'll love it!_

== Quickstart

=== Install

[source,bash]
----
npm install --save-dev @openzeppelin/test-environment
----

=== Usage

Simply `require('@openzeppelin/test-environment')` in your test files, and it will take care of all Ethereum-related tasks. A local https://github.com/trufflesuite/ganache-core[ganache-powered blockchain] with unlocked accounts will be spun up, and all tools will be configured to work with it.

[source,javascript]
----
const { accounts, contract } = require('@openzeppelin/test-environment');
const [ tokenHolder ] = accounts;

const ERC20 = contract.fromArtifact('ERC20'); // Loads a compiled contract

async function test() {
  const token = await ERC20.new({ from: tokenHolder });
  const initialBalance = await token.balanceOf(tokenHolder);
}
----

_Note: if you'd rather not rely on truffle contracts and use web3 contract types directly, worry not: you can xref:setup.adoc#configuration[configure `test-environment`] to use the `web3-eth-contract` abstraction._

== Documentation

* xref:api.adoc[API Reference]
* xref:migrate-from-truffle.adoc[Migrate from Truffle]
* xref:setup.adoc[Setting up Your Project]
* xref:test-runners.adoc[Test Runners]
