= Migrating from `truffle test`

Despite Truffle's design and goals being different from `test-environment` 's (one is an all-out development framework and the other a testing library), it is still quite simple to migrate from a `truffle test`-based suite. Doing the whole process on the OpenZeppelin Contracts repository took less than thirty minutes!

Because `truffle test` uses a lightly modified Mocha as a test runner (bundled with Chai for assertions), these two make best choice for a simple migration:

[source,bash]
----
npm install --save-dev mocha chai
----

Don't forget to make Mocha the entry point of your test suite once you install it:

[source,diff]
----
// in package.json
 "scripts": {
-  "test": "npx truffle test"
+  "test": "npx mocha --exit --recursive test"
 }
----

_Note: the `--exit` flag is required when using truffle contracts. Otherwise, the test suite will not exit._

It is now time to modify the test files themselves. The changes are few, but important: 

1. Add `require('@openzeppelin/test-environment')` to access the variables exported by the library: `accounts`, `contract`, `web3`, etc. 
2. `truffle test` automagically imports Chai: you will need to `require` it and set it up manually 
3. Replace all instances of `artifacts.require` for `contract.fromArtifact` 
4. Replace all intances of `truffle test` 's `contract` function with a regular Mocha `describe`. You can still access the accounts array in `accounts`

That's it! Let's see what a full migration might look like:

[source,diff]
----
+const { accounts, contract, web3 } = require('@openzeppelin/test-environment');

 // Setup Chai for 'expect' or 'should' style assertions (you only need one)
+const { expect } = require('chai');
+require('chai').should();

-const ERC20 = artifacts.require('ERC20');
+const ERC20 = contract.fromArtifact('ERC20');

-contract('ERC20', function (accounts) {
+describe('ERC20', function () {
   ...
 }
----

You are now ready to start using `test-environment` by running `npm test`. Enjoy lightning fast testing!
