= Setting up Your Project

== Test runners

`test-environment` is a testing _library_, something you use _in_ your tests, as opposed to what actually _runs_ them. For that, you are free to use any regular JavaScript test runner. We recommend picking one of the following:

* https://mochajs.org/[Mocha]: simple and straightforward, the easiest way to get started when migrating from `truffle test`
* https://jestjs.io/[Jest]: the most popular runner out there, featuring lightning speed, parallel tests, and extensive guides
* https://www.npmjs.com/package/ava/[Ava]: a minimalistic runner with parallel tests and support for ES6 and TypeScript

Both Jest and Ava have their own assertions library, but for Mocha, you may want to also use https://www.chaijs.com[Chai].

Head to our xref:test-runners.adoc[test runners guide] to learn more about how to setup each one.

== Compiling your contracts

`test-environment` is not a contract compiler. You can use the https://docs.openzeppelin.com/sdk[OpenZeppelin CLI] to compile your Solidity files just as easily.

[source,bash]
----
npm install --save-dev @openzeppelin/cli
npx oz compile
----

Compilation artifacts will be stored in the `build/contracts` directory, where `testing-environment` (and most other tools) will read them from.

== OpenZeppelin https://github.com/OpenZeppelin/openzeppelin-test-helpers[Test Helpers] support

`testing-environment` does not include the Test Helpers library, but it will automatically detect it and configure it if it is installed. Simply `require('@openzeppelin/test-helpers')` and use it as you already do.

[configuration]
== Configuration

The default options are very sensible and should work fine for most testing setups, but you are free to modify these. Simply create a file named `test-environment.config.js` at the root level of your project: its contents will be automatically loaded.

[source,javascript]
----
module.exports = {
  accounts: {
    amount: 10, // Number of unlocked accounts
    ether: 100, // Initial balance of unlocked accounts (in ether)
  },

  contracts: {
    type: 'truffle', // Contract abstraction to use: 'truffle' for @truffle/contract or 'web3' for web3-eth-contract
    defaultGas: 6e6, // Maximum gas for contract calls (when unspecified)
  },

  blockGasLimit: 8e6, // Maximum gas per block
};
----
